import FontDetector from '../../utils/FontDetector';

const detector = new FontDetector();

// Include base fonts seperately since they get filtered out of our font detector.
const baseFonts = ['monospace', 'sans', 'sans-serif'];
// List of typefaces commonly included with Windows/MacOS.
// Yes some are god awful, but were not trying to be opinionated here.
const fonts = [
  'Agency FB',
  'American Typewriter',
  'Andale Mono',
  'Arial',
  'Arial Black',
  'Avenir',
  'Bahnschrift',
  'Baskerville',
  'Bauhaus 93',
  'Bell MT',
  'Berlin Sans FB',
  'Big Caslon',
  'Bodoni MT',
  'Book Antiqua',
  'Brush Script MT',
  'Calibri',
  'Calibri Light',
  'Calisto MT',
  'Cambria',
  'Candara',
  'Century Gothic',
  'Chalkboard',
  'Chalkduster',
  'Chiller',
  'Cochin',
  'Colonna MT',
  'Comic Sans MS',
  'Consolas',
  'Constantia',
  'Cooper Black',
  'Copperplate',
  'Copperplate Gothic Bold',
  'Copperplate Gothic Light',
  'Corbel',
  'Courier',
  'Courier New',
  'Curlz MT',
  'Didot',
  'Forte',
  'Freestyle Script',
  'French Script MT',
  'Futura',
  'Gabriola',
  'Geneva',
  'Georgia',
  'Gigi',
  'Gill Sans',
  'Gill Sans MT',
  'Goudy Old Style',
  'Helvetica',
  'Helvetica Neue',
  'Herculanum',
  'High Tower Text',
  'Impact',
  'Iowan Old Style',
  'Lucida Console',
  'Lucida Grande',
  'Lucida Handwriting',
  'Lucida Sans Unicode',
  'Marker Felt',
  'Menlo',
  'Microsoft Sans Serif',
  'Monaco',
  'Onyx',
  'Optima',
  'Palace Script MT',
  'Palatino',
  'Palatino Linotype',
  'Papyrus',
  'Pristina',
  'Ravie',
  'Rockwell',
  'Sathu',
  'Script MT Bold',
  'Segoe Print',
  'Segoe Script',
  'Segoe UI',
  'Sitka',
  'Sitka Banner',
  'Sitka Display',
  'Sitka Heading',
  'Sitka Small',
  'Sitka Subheading',
  'Sitka Text',
  'Skia',
  'Tahoma',
  'Times New Roman',
  'Trebuchet MS',
  'Tw Cen MT',
  'Verdana',
  'Wide Latin',
  'Zapfino',
];

const availableFonts = [
  ...baseFonts,
  ...fonts.filter(font => detector.detect(font)),
];

export default availableFonts;
